<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dad_jokes.proto

namespace DadJoke;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DadJoke.DadJokeResponse</code>
 */
class DadJokeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string joke = 1;</code>
     */
    private $joke = '';

    public function __construct() {
        \GPBMetadata\DadJokes::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string joke = 1;</code>
     * @return string
     */
    public function getJoke()
    {
        return $this->joke;
    }

    /**
     * Generated from protobuf field <code>string joke = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJoke($var)
    {
        GPBUtil::checkString($var, True);
        $this->joke = $var;

        return $this;
    }

}

