# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dad_jokes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "DadJoke.DadJokeRequest" do
    optional :keyword, :string, 1
  end
  add_message "DadJoke.DadJokeResponse" do
    optional :joke, :string, 1
  end
end

module DadJoke
  DadJokeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("DadJoke.DadJokeRequest").msgclass
  DadJokeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("DadJoke.DadJokeResponse").msgclass
end
