<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dad_jokes.proto

namespace GPBMetadata;

class DadJokes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab4010a0f6461645f6a6f6b65732e70726f746f12074461644a6f6b6522" .
            "210a0e4461644a6f6b6552657175657374120f0a076b6579776f72641801" .
            "20012809221f0a0f4461644a6f6b65526573706f6e7365120c0a046a6f6b" .
            "65180120012809324c0a074461644a6f6b6512410a0a4765744461644a6f" .
            "6b6512172e4461644a6f6b652e4461644a6f6b65526571756573741a182e" .
            "4461644a6f6b652e4461644a6f6b65526573706f6e73652200620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

